source 'https://rubygems.org'

gem 'fluent-plugin-concat'
gem 'fluent-plugin-detect-exceptions'
gem 'fluent-plugin-elasticsearch'
gem 'fluent-plugin-multi-format-parser'
gem 'fluent-plugin-prometheus'
gem 'fluent-plugin-systemd'
gem 'oj'
gem 'fluent-plugin-ignore-filter'
gem 'fluent-plugin-grok-parser'
